
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/App/MinGW/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/Users/食草龙/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/3.31.0/CompilerIdC/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/\u98df\u8349\u9f99/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-2wc9gp"
      binary: "C:/Users/\u98df\u8349\u9f99/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-2wc9gp"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/食草龙/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-2wc9gp'
        
        Run Build Command(s): D:/App/CMake/bin/cmake.exe -E env VERBOSE=1 D:/App/CMake/bin/cmake.exe -f Makefile cmTC_f9934/fast
        CMake Warning:
          Ignoring extra path from command line:
        
           "cmTC_f9934/fast"
        
        
        CMake Error: Unknown argument -f
        CMake Error: Run 'cmake --help' for all supported options.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/App/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Check for working C compiler: D:/App/MinGW/bin/gcc.exe"
    directories:
      source: "C:/Users/\u98df\u8349\u9f99/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-l80d9a"
      binary: "C:/Users/\u98df\u8349\u9f99/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-l80d9a"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/食草龙/Desktop/github/CSAPP/datalab-handout/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-l80d9a'
        
        Run Build Command(s): D:/App/CMake/bin/cmake.exe -E env VERBOSE=1 D:/App/CMake/bin/cmake.exe -f Makefile cmTC_5a57a/fast
        CMake Warning:
          Ignoring extra path from command line:
        
           "cmTC_5a57a/fast"
        
        
        CMake Error: Unknown argument -f
        CMake Error: Run 'cmake --help' for all supported options.
        
      exitCode: 1
...
